subject=set()
print("1.add new subject")
print("2.remove a subject")
print("3.display all subjects")
print("4.show total number of unique subjects")
sub=input("enter the subject name:")
subject.add(sub)
print("subject added")
cub=input("enter the subject to remove")
subject.remove(sub)
print("the subjects are of the follows:")
print(subject)
print("the number of unique subjects are:",len(subject))